if [[ $TILIX_ID ]]; then
    # source /etc/profile.d/vte.sh
    source /etc/profile.d/vte-2.91.sh
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="agnoster"
# ZSH_THEME="avit"
# ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_THEME="zen"

# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
# ZSH_THEME=random

# to use case-sensitive completion.
# CASE_SENSITIVE="true"

# to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# to disable colors in ls.
# DISABLE_LS_COLORS="true"

# to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# to enable command auto-correction.
# ENABLE_CORRECTION="true"

# to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

export DEFAULT_USER=`whoami`

# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# too many plugins slow down shell startup.
# plugins=(colorize cp git ssh-agent per-directory-history docker docker-compose svn-fast-info) # ^G to active per directory history

plugins=(colorize cp git)
DISABLE_UNTRACKED_FILES_DIRTY="true"

source $ZSH/oh-my-zsh.sh

# default = global history
# _per-directory-history-set-global-history


zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa workkey id_pharos id_vps
zstyle :omz:plugins:ssh-agent lifetime 4h

# this option causes globs which do not match a file to result in an error without running the command.
# If unset, the command is run with the un-expanded glob.
unsetopt nomatch

# You may need to manually set your language environment
# /etc/default/locale
#export LC_ALL=fr_FR.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export PAPERSIZE=a4
# export LC_IDENTIFICATION=fr_FR.UTF-8
export LC_MEASUREMENT=fr_FR.UTF-8
#export LC_NUMERIC=fr_FR.UTF-8
export LC_TIME=fr_FR.UTF-8
export LC_PAPER=fr_FR.UTF-8
export LC_MONETARY=fr_FR.UTF-8
export LC_TELEPHONE=fr_FR.UTF-8
export LC_NAME=fr_FR.UTF-8
export LC_ADDRESS=fr_FR.UTF-8
# LC_COLLATE=
# LC_NAME=

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='code'
fi

# ===================
# Luc's specifities
# ===================

# aliases
if [[ -s $HOME/.dotfiles/zsh/aliasrc ]] ; then
    source $HOME/.dotfiles/zsh/aliasrc
fi

if [[ -s $HOME/.dotfiles/zsh/bookmarks.zsh ]] ; then
    source $HOME/.dotfiles/zsh/bookmarks.zsh
fi

# export MANPATH="/usr/local/man:$MANPATH"

export PUID=`id -u`
export PGID=`id -g`

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# export PILLAR_HOME="$HOME/Pharo/Booklets/Pillar.git"

# export PATH=$HOME/.local/bin:/home/luc/.platformio/penv/bin:$PATH
export PATH="$PATH:$HOME/.local/bin"
#export PATH="$PATH:$HOME/.local/bin:/home/luc/.platformio/penv/bin:/home/luc/.local/share/flutter/bin"

# export PATH="$HOME/.local/share/android-studio/bin:$PATH"
export ANDROID_HOME="$HOME/.local/share/android-sdk"

if [[ -s $HOME/.zshrc_private ]] ; then
    source $HOME/.zshrc_private
fi